# Generated by Django 6.0.3 on 2026-03-26 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('available_beds', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='room_number',
        ),
        migrations.AddField(
            model_name='student',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.room'),
            preserve_default=False,
        ),
    ]
